ci(egui): Select xdg-portal as backend for egui
Error message:
error: failed to run custom build command for `rfd v0.15.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/woodpecker/src/codeberg.org/topola/topola/target/debug/build/rfd-df83cee8e4039bcf/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.15.1/build.rs:14:17:
  You need to choose at least one backend: `gtk3` or `xdg-portal` features